In [121]:
from numpy import *

#problem 6

a = np.array([[2, -1, 0, 0],
           [-1, 2, -1, 0],
           [0, -1, 2, -1],
           [0, 0, -1, 2]],float)
b = np.array([0.2, 0.4, 0.6, 0.8], float)
n = len(b)
x = np.zeros(n, float)

#forward elimination
for k in range(n-1):
    for i in range(k+1, n):
        fctr = a[i, k] / a[k, k]
        for j in range(k, n):
            a[i, j] = a[i, j] - fctr*a[k, j]
        b[i] = b[i] - fctr*b[k]
        
#back-subst.
x[n-1] = b[n-1] / a[n-1, n-1]
for i in range(n-2, -1, -1):
  Sum = b[i]
  for j in range(i+1, n):
      Sum = Sum - a[i, j]*x[j]
  x[i] = Sum/a[i, i]
  
print('Results: g vector')
print(x)

# making the tridiagonal matrix
nXn = 6
a = zeros((nXn, nXn), dtype=float)
u = len(a)
for i in range(u):
    for j in range(len(a[i])):
        if i == j:
            a[i][j] = 2
        elif i - j == -1 or i-j == 1:
            a[i][j]=-1
        else:
            a[i][j] = 0

#making the v_i vector with equal stepsize:

b = [0]*len(a)
for i in range(u):
    b[i] = i/(1+len(a)) +1/(len(a)+1)

n=len(a)

print("matrix A", len(a),"x",len(a),"matrix")
print(a)
print("vector v") #steps
print(b)


x = np.zeros(n, float)

#forward elimination
for k in range(n-1):
    for i in range(k+1, n):
        fctr = a[i, k] / a[k, k]
        for j in range(k, n):
            a[i, j] = a[i, j] - fctr*a[k, j]
        b[i] = b[i] - fctr*b[k]
        
#back-subst.
x[n-1] = b[n-1] / a[n-1, n-1]
for i in range(n-2, -1, -1):
  Sum = b[i]
  for j in range(i+1, n):
      Sum = Sum - a[i, j]*x[j]
  x[i] = Sum/a[i, i]
  
print('Results: vector g')
print(x)


Results: g vector
[0.8 1.4 1.6 1.2]
matrix A 6 x 6 matrix
[[ 2. -1.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0. -1.  2.]]
vector v
[0.14285714285714285, 0.2857142857142857, 0.42857142857142855, 0.5714285714285714, 0.7142857142857142, 0.8571428571428572]
Results: vector g
[1.14285714 2.14285714 2.85714286 3.14285714 2.85714286 1.85714286]
